### ISSUE TITLE
magc: centre_sx_sy must be set after update_tile_position

### ISSUE THREAD

**Issue by templiert** [SBEMimage/SBEMimage#38]
After [this commit](https://github.com/SBEMimage/SBEMimage/commit/4c287ec1e51547c8d520a0328fdff53a6ccb7221) there was something wrong with the positioning of MagC grids.

The issue [was solved here](https://github.com/SBEMimage/SBEMimage/commit/d834944304fc4894883e23890cef0f7f187ef661) by setting centre_sx_sy after update_tile_position(). Just mentioning it here to make sure that it was the intended behavior of update_tile_position?

**Comment by btitze** [comment]
Everything is working as intended, but you are right that tile positions must be updated before setting centre_sx_sy. 

By default, when auto_update_tile_positions is set to True, the tile positions are always automatically updated whenever certain grid attributes are changed.

When changing several grid attributes at once, like in the grid settings dialog or your MagC import dialog, it can make sense to first update all attributes, and then update the tile positions only once. 

But this does not work for setting centre_sx_sy because that setter needs the current tile positions to calculate to the current centre_sx_sy. Thanks for spotting that. Your updated code is correct. I will add an explanation in grid_manager.
